import type { Profile, Experience, Project, Skill } from './types'

export const seedProfile: Profile = {
  id: 1,
  name: 'Bao Pham',
  title: 'Software Engineer',
  tagline: 'Building robust systems at the intersection of product, AI, and engineering.',
  bio: "I'm a full-stack software engineer specializing in TypeScript/JavaScript across the entire stack — from NestJS APIs and SQS workers to Next.js frontends. I enjoy tackling complex integrations, AI-powered systems, and real-time features. I care about clean architecture, good DX, and shipping things that work.",
  email: 'hello@baopham.dev',
  github: 'https://github.com/baopham',
  linkedin: 'https://linkedin.com/in/baopham',
  twitter: 'https://twitter.com/baopham',
  location: 'San Francisco, CA',
  years_experience: 3,
  projects_count: 10,
}

export const seedExperience: Experience[] = [
  {
    id: 1,
    company: 'Paratus Health',
    role: 'Software Engineer (Full-Stack)',
    start_date: '2022-04',
    end_date: undefined,
    is_current: true,
    description:
      'Building an AI-powered healthcare communications platform. Shipped NestJS microservice APIs, SQS-based async workers, EHR integrations (eClinicalWorks, Athena, WebPT), AI voice call scheduling via Retell, real-time audio/video with LiveKit, and Langfuse-instrumented LLM pipelines. Also built patient-facing and provider-facing Next.js 15 frontends in a Turborepo monorepo.',
    tech_stack: [
      'NestJS',
      'Node.js',
      'TypeScript',
      'PostgreSQL',
      'Redis',
      'AWS SQS',
      'AWS S3',
      'Next.js',
      'React',
      'Turborepo',
      'Docker',
      'OpenAI',
      'Langfuse',
      'Prisma',
      'Fastify',
    ],
    sort_order: 1,
    company_url: 'https://paratushealth.com',
    logo_color: '#059669',
  },
  {
    id: 2,
    company: 'Nimbus Labs',
    role: 'Full-Stack Engineer',
    start_date: '2020-08',
    end_date: '2022-03',
    is_current: false,
    description:
      'Joined as the second engineer at a B2B SaaS startup building workflow automation tools. Designed and shipped a multi-tenant REST API with Express and Prisma, a drag-and-drop workflow builder in React, and a Zapier-style webhook engine. Led migration from a monolith to a service-oriented architecture.',
    tech_stack: ['React', 'TypeScript', 'Node.js', 'Express', 'Prisma', 'PostgreSQL', 'Redis', 'AWS EC2', 'Stripe'],
    sort_order: 2,
    company_url: 'https://nimbuslabs.io',
    logo_color: '#6366F1',
  },
  {
    id: 3,
    company: 'Accenture',
    role: 'Software Engineer (Associate)',
    start_date: '2019-01',
    end_date: '2020-07',
    is_current: false,
    description:
      'Consulted for enterprise clients across fintech and retail verticals. Built internal tooling dashboards in React, maintained Java Spring Boot microservices, and contributed to CI/CD pipeline improvements that cut deployment time by ~35%. Passed AWS Solutions Architect associate exam.',
    tech_stack: ['React', 'Java', 'Spring Boot', 'Jenkins', 'AWS', 'SQL Server', 'Docker'],
    sort_order: 3,
    company_url: 'https://accenture.com',
    logo_color: '#A855F7',
  },
]

export const seedProjects: Project[] = [
  {
    id: 1,
    featured: true,
    sort_order: 1,
    year: 2022,
    color: '#059669',
    title: 'Paratus Service Platform',
    description:
      'Scalable NestJS + Fastify backend for an AI healthcare platform. Dual-entrypoint (API + SQS worker), EHR integrations (eClinicalWorks, Athena, WebPT), AI voice scheduling via Retell, real-time LiveKit sessions, Langfuse-traced LLM pipelines, Redis caching, Stripe billing, and DataDog metrics.',
    tech_stack: [
      'NestJS',
      'Fastify',
      'Prisma',
      'PostgreSQL',
      'Redis',
      'AWS SQS',
      'AWS S3',
      'OpenAI',
      'Langfuse',
      'Pinecone',
      'Retell',
      'LiveKit',
      'Stripe',
    ],
    github_url: undefined,
    live_url: undefined,
  },
  {
    id: 2,
    featured: true,
    sort_order: 2,
    year: 2022,
    color: '#2563EB',
    title: 'Paratus Web Platform',
    description:
      'Turborepo monorepo with two Next.js 15 apps — patient-facing portal and provider dashboard — sharing UI/utils packages. Features real-time audio via LiveKit, Deepgram speech-to-text, Mapbox maps, Recharts analytics, TanStack Query, and Playwright e2e tests.',
    tech_stack: [
      'Next.js',
      'React 19',
      'TypeScript',
      'Turborepo',
      'TailwindCSS',
      'LiveKit',
      'Deepgram',
      'Mapbox',
      'TanStack Query',
      'Playwright',
      'Docker',
    ],
    github_url: undefined,
    live_url: undefined,
  },
  {
    id: 3,
    featured: false,
    sort_order: 3,
    year: 2025,
    color: '#D97706',
    title: 'Portfolio v3',
    description:
      'Personal portfolio built with Next.js 16 App Router, a custom 3D robot mascot (react-three/fiber), Framer Motion panel transitions, Turso edge database, and full SEO setup. Designed and built from scratch.',
    tech_stack: ['Next.js', 'TypeScript', 'Three.js', 'Framer Motion', 'TailwindCSS', 'Turso'],
    github_url: 'https://github.com/baopham/portfolio-v3',
    live_url: 'https://phambao.dev',
  },
  {
    id: 4,
    featured: false,
    sort_order: 4,
    year: 2024,
    color: '#6366F1',
    title: 'FlowForge',
    description:
      'Open-source CLI + Node.js library for scaffolding opinionated NestJS projects. Generates modules, services, DTOs, and Prisma schemas from a single config file. 300+ GitHub stars.',
    tech_stack: ['Node.js', 'TypeScript', 'NestJS', 'Prisma', 'Commander.js'],
    github_url: 'https://github.com/baopham/flowforge',
    live_url: undefined,
  },
  {
    id: 5,
    featured: false,
    sort_order: 5,
    year: 2023,
    color: '#0891B2',
    title: 'Logdash',
    description:
      'Lightweight self-hosted log aggregator with a real-time web UI. Ingests structured logs via HTTP, stores them in SQLite, and streams updates over WebSockets. Single binary deploy via Docker.',
    tech_stack: ['Fastify', 'TypeScript', 'SQLite', 'WebSockets', 'React', 'Docker'],
    github_url: 'https://github.com/baopham/logdash',
    live_url: undefined,
  },
  {
    id: 6,
    featured: false,
    sort_order: 6,
    year: 2023,
    color: '#E11D48',
    title: 'Nudge',
    description:
      'A habit-tracking PWA with streaks, reminders, and a weekly heatmap. Built as a weekend project to explore React Server Components and the new Next.js App Router patterns before using them in production.',
    tech_stack: ['Next.js', 'TypeScript', 'TailwindCSS', 'Drizzle', 'PostgreSQL', 'Vercel'],
    github_url: 'https://github.com/baopham/nudge',
    live_url: 'https://nudge.phambao.dev',
  },
]

export const seedSkills: Skill[] = [
  // Frontend
  { id: 1, name: 'React', category: 'Frontend', proficiency: 95, sort_order: 1 },
  { id: 2, name: 'Next.js', category: 'Frontend', proficiency: 95, sort_order: 2 },
  { id: 3, name: 'TypeScript', category: 'Frontend', proficiency: 92, sort_order: 3 },
  { id: 4, name: 'TailwindCSS', category: 'Frontend', proficiency: 90, sort_order: 4 },
  { id: 5, name: 'Framer Motion', category: 'Frontend', proficiency: 82, sort_order: 5 },

  // Backend
  { id: 6, name: 'Node.js', category: 'Backend', proficiency: 90, sort_order: 1 },
  { id: 7, name: 'NestJS', category: 'Backend', proficiency: 90, sort_order: 2 },
  { id: 8, name: 'Fastify', category: 'Backend', proficiency: 85, sort_order: 3 },
  { id: 9, name: 'Prisma', category: 'Backend', proficiency: 88, sort_order: 4 },
  { id: 10, name: 'PostgreSQL', category: 'Backend', proficiency: 85, sort_order: 5 },
  { id: 11, name: 'Redis', category: 'Backend', proficiency: 80, sort_order: 6 },
  { id: 12, name: 'REST APIs', category: 'Backend', proficiency: 95, sort_order: 7 },

  // Cloud/DevOps
  { id: 13, name: 'AWS SQS', category: 'Cloud/DevOps', proficiency: 85, sort_order: 1 },
  { id: 14, name: 'AWS S3', category: 'Cloud/DevOps', proficiency: 85, sort_order: 2 },
  { id: 15, name: 'Docker', category: 'Cloud/DevOps', proficiency: 80, sort_order: 3 },
  { id: 16, name: 'GitHub Actions', category: 'Cloud/DevOps', proficiency: 82, sort_order: 4 },
  { id: 17, name: 'CI/CD', category: 'Cloud/DevOps', proficiency: 80, sort_order: 5 },

  // AI/Integrations
  { id: 18, name: 'OpenAI', category: 'AI/Integrations', proficiency: 85, sort_order: 1 },
  { id: 19, name: 'Langfuse', category: 'AI/Integrations', proficiency: 80, sort_order: 2 },
  { id: 20, name: 'Pinecone', category: 'AI/Integrations', proficiency: 75, sort_order: 3 },
  { id: 21, name: 'LiveKit', category: 'AI/Integrations', proficiency: 80, sort_order: 4 },
]
