import type { Profile, Experience, Project, Skill } from './types'

export const seedProfile: Profile = {
  id: 1,
  name: 'Pham Hoang Bao',
  title: 'Software Engineer',
  tagline: 'Building robust systems at the intersection of AI, healthcare, and full-stack engineering.',
  bio: "Full-stack software engineer with 4+ years of experience building production systems end-to-end — from backend APIs and Python microservices to real-time frontends and cloud infrastructure. I enjoy complex integrations, AI-powered products, and shipping things that work at scale.",
  email: 'phamhoangbao2710@gmail.com',
  github: 'https://github.com/baophamhoang',
  linkedin: 'https://linkedin.com/in/baophamhoang',
  twitter: undefined,
  location: 'Da Nang, Vietnam',
  years_experience: 4,
  projects_count: 12,
}

export const seedExperience: Experience[] = [
  {
    id: 1,
    company: 'Spartan',
    role: 'Software Engineer',
    start_date: '2025-04',
    end_date: undefined,
    is_current: true,
    description:
      'Building an AI-powered healthcare communications platform (Paratus Health). Shipped NestJS microservice APIs, SQS-based async workers, EHR integrations (eClinicalWorks, Athena, WebPT, OpenDental), AI voice call scheduling via Retell, real-time audio/video with LiveKit, and Langfuse-instrumented LLM pipelines. Also built a Python RPA service for EHR browser automation, a LiveKit voice agent microservice with OpenAI/Deepgram, and managed Terraform/EKS infrastructure. Frontend delivered via a Turborepo monorepo with two Next.js 15 apps.',
    tech_stack: [
      'NestJS',
      'TypeScript',
      'Python',
      'FastAPI',
      'Next.js',
      'React',
      'PostgreSQL',
      'Redis',
      'AWS SQS',
      'AWS S3',
      'Terraform',
      'Kubernetes',
      'Docker',
      'LiveKit',
      'OpenAI',
      'Prisma',
      'Selenium',
      'Turborepo',
    ],
    sort_order: 1,
    company_url: 'https://spartan.io',
    logo_color: '#F59E0B',
  },
  {
    id: 2,
    company: 'Datahouse Asia',
    role: 'Software Engineer',
    start_date: '2022-02',
    end_date: '2025-03',
    is_current: false,
    description:
      'Delivered production systems for enterprise clients across ERP and government verticals. Built VizERP — a multi-tenant ERP platform with ReactFlow BPMN diagrams, AWS S3/Lambda integrations, and an internal permission management package that reduced auth token size by 75%. Also delivered DLIR UI, a government unemployment claims system with SOAP payment integrations and AngularJS-to-Angular migration.',
    tech_stack: [
      'React',
      'Angular',
      'TypeScript',
      'NestJS',
      'Node.js',
      'PostgreSQL',
      'Prisma',
      'TypeORM',
      'AWS S3',
      'AWS Lambda',
      'ReactFlow',
      'RxJS',
      'Docker',
      'GitHub Actions',
    ],
    sort_order: 2,
    company_url: 'https://datahouse-asia.com',
    logo_color: '#0EA5E9',
  },
  {
    id: 3,
    company: 'Unitech',
    role: 'R&D Intern',
    start_date: '2020-06',
    end_date: '2020-08',
    is_current: false,
    description: 'Researched IoT devices and AI applications. Worked on small-scale image processing projects.',
    tech_stack: ['Python', 'IoT'],
    sort_order: 3,
    company_url: undefined,
    logo_color: '#6B7280',
  },
]

export const seedProjects: Project[] = [
  {
    id: 1,
    featured: true,
    sort_order: 1,
    year: 2025,
    color: '#059669',
    title: 'Paratus Service Platform',
    description:
      'Scalable NestJS + Fastify backend for an AI healthcare communications platform. Dual-entrypoint architecture (API + SQS worker), EHR integrations (eClinicalWorks, Athena, WebPT, OpenDental), AI voice scheduling via Retell, real-time LiveKit sessions, Langfuse-traced LLM pipelines, Redis caching, Stripe billing, and Datadog metrics.',
    tech_stack: [
      'NestJS',
      'Fastify',
      'Prisma',
      'PostgreSQL',
      'Redis',
      'AWS SQS',
      'AWS S3',
      'OpenAI',
      'Langfuse',
      'Pinecone',
      'Retell',
      'LiveKit',
      'Stripe',
    ],
    github_url: undefined,
    live_url: undefined,
  },
  {
    id: 2,
    featured: true,
    sort_order: 2,
    year: 2025,
    color: '#DC2626',
    title: 'RPA Automation Service',
    description:
      'Python FastAPI microservice for healthcare EHR automation. Uses undetected-chromedriver to bypass Cloudflare bot detection and automate eClinicalWorks patient creation workflows. Chrome instance pooling for concurrency, PyOTP for 2FA, SQS consumer for async processing.',
    tech_stack: ['Python', 'FastAPI', 'Selenium', 'PostgreSQL', 'AWS SQS', 'Docker'],
    github_url: undefined,
    live_url: undefined,
  },
  {
    id: 3,
    featured: true,
    sort_order: 3,
    year: 2022,
    color: '#6366F1',
    title: 'VizERP',
    description:
      'Multi-tenant ERP platform covering Admin, Core, Timekeeping, and Recruitment modules. Reduced auth token size by 75%. Built internal permission management package, ReactFlow BPMN diagram editor, and multi-tenant navigation system. AWS S3/Lambda for scalability.',
    tech_stack: ['React', 'NestJS', 'TypeScript', 'PostgreSQL', 'Prisma', 'AWS S3', 'AWS Lambda', 'ReactFlow', 'RxJS', 'Redux'],
    github_url: undefined,
    live_url: undefined,
  },
  {
    id: 4,
    featured: false,
    sort_order: 4,
    year: 2025,
    color: '#2563EB',
    title: 'LiveKit Voice Agent',
    description:
      'Python FastAPI microservice providing AI voice agents for healthcare workflows — general assistant, medical intake specialist, and appointment scheduler. Integrates LiveKit Cloud, OpenAI, Deepgram (STT), and Cartesia (TTS). Phone call support via SIP trunk.',
    tech_stack: ['Python', 'FastAPI', 'LiveKit', 'OpenAI', 'Deepgram', 'Cartesia', 'Docker'],
    github_url: undefined,
    live_url: undefined,
  },
  {
    id: 5,
    featured: false,
    sort_order: 5,
    year: 2025,
    color: '#D97706',
    title: 'Fatefolio',
    description:
      'AI-powered fortune reading platform. Users receive personalized readings and personal AI assistant as a fortune teller. Supports EN/VI, PayOS payments, NextAuth authentication, Upstash rate limiting, and Sentry monitoring.',
    tech_stack: ['Next.js', 'TypeScript', 'OpenAI', 'Drizzle', 'Neon', 'NextAuth', 'PayOS', 'TailwindCSS', 'Framer Motion'],
    github_url: undefined,
    live_url: undefined,
  },
  {
    id: 6,
    featured: false,
    sort_order: 6,
    year: 2024,
    color: '#0891B2',
    title: 'Odia',
    description:
      'Private group photo vault — upload, organize into folders/runs, control access via whitelist, manage with admin dashboard. AWS S3 for storage with presigned URLs, NextAuth authentication, Turso SQLite.',
    tech_stack: ['Next.js', 'TypeScript', 'AWS S3', 'NextAuth', 'Turso', 'Drizzle', 'TailwindCSS'],
    github_url: undefined,
    live_url: undefined,
  },
  {
    id: 7,
    featured: false,
    sort_order: 7,
    year: 2025,
    color: '#16A34A',
    title: 'Chips Tracker',
    description:
      'Real-time collaborative poker chip tracker. Create or join rooms with a code, track player stacks live via Supabase realtime subscriptions. Mobile-first with EN/VI support.',
    tech_stack: ['Next.js', 'TypeScript', 'Supabase', 'TailwindCSS'],
    github_url: undefined,
    live_url: undefined,
  },
]

export const seedSkills: Skill[] = [
  // Frontend
  { id: 1, name: 'React', category: 'Frontend', proficiency: 95, sort_order: 1 },
  { id: 2, name: 'Next.js', category: 'Frontend', proficiency: 95, sort_order: 2 },
  { id: 3, name: 'TypeScript', category: 'Frontend', proficiency: 92, sort_order: 3 },
  { id: 4, name: 'TailwindCSS', category: 'Frontend', proficiency: 90, sort_order: 4 },
  { id: 5, name: 'Angular', category: 'Frontend', proficiency: 80, sort_order: 5 },
  { id: 6, name: 'RxJS', category: 'Frontend', proficiency: 78, sort_order: 6 },

  // Backend
  { id: 7, name: 'Node.js', category: 'Backend', proficiency: 90, sort_order: 1 },
  { id: 8, name: 'NestJS', category: 'Backend', proficiency: 92, sort_order: 2 },
  { id: 9, name: 'Python', category: 'Backend', proficiency: 82, sort_order: 3 },
  { id: 10, name: 'FastAPI', category: 'Backend', proficiency: 80, sort_order: 4 },
  { id: 11, name: 'Fastify', category: 'Backend', proficiency: 85, sort_order: 5 },
  { id: 12, name: 'Prisma', category: 'Backend', proficiency: 88, sort_order: 6 },
  { id: 13, name: 'PostgreSQL', category: 'Backend', proficiency: 85, sort_order: 7 },
  { id: 14, name: 'Redis', category: 'Backend', proficiency: 80, sort_order: 8 },
  { id: 15, name: 'REST APIs', category: 'Backend', proficiency: 95, sort_order: 9 },

  // Cloud/DevOps
  { id: 16, name: 'AWS SQS', category: 'Cloud/DevOps', proficiency: 85, sort_order: 1 },
  { id: 17, name: 'AWS S3', category: 'Cloud/DevOps', proficiency: 85, sort_order: 2 },
  { id: 18, name: 'Docker', category: 'Cloud/DevOps', proficiency: 82, sort_order: 3 },
  { id: 19, name: 'GitHub Actions', category: 'Cloud/DevOps', proficiency: 82, sort_order: 4 },
  { id: 20, name: 'Terraform', category: 'Cloud/DevOps', proficiency: 76, sort_order: 5 },
  { id: 21, name: 'Kubernetes', category: 'Cloud/DevOps', proficiency: 74, sort_order: 6 },
  { id: 22, name: 'CI/CD', category: 'Cloud/DevOps', proficiency: 80, sort_order: 7 },

  // AI/Integrations
  { id: 23, name: 'OpenAI', category: 'AI/Integrations', proficiency: 85, sort_order: 1 },
  { id: 24, name: 'Langfuse', category: 'AI/Integrations', proficiency: 78, sort_order: 3 },
  { id: 25, name: 'LiveKit', category: 'AI/Integrations', proficiency: 82, sort_order: 2 },
  { id: 26, name: 'Selenium/RPA', category: 'AI/Integrations', proficiency: 80, sort_order: 4 },
]
